
package com.epam.web.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LibraryService", targetNamespace = "http://soap.web.epam.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryService extends com.epam.web.LibraryService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.epam.web.soap.Book>
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBooksByAuthor", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetBooksByAuthor")
    @ResponseWrapper(localName = "getBooksByAuthorResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetBooksByAuthorResponse")
    public List<Book> getBooksByAuthor(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServiceException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteBook", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.DeleteBook")
    @ResponseWrapper(localName = "deleteBookResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.DeleteBookResponse")
    public boolean deleteBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.epam.web.soap.Book>
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetAllBooksResponse")
    public List<Book> getAllBooks()
        throws ServiceException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.web.soap.Book
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBook", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.GetBookResponse")
    public Book getBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServiceException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws ServiceException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://soap.web.epam.com/", className = "com.epam.web.soap.AddBookResponse")
    public boolean addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0)
        throws ServiceException
    ;

}
